version: "3.8"

services:
  radiation_monitor_api:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: python main.py
